name: 5-minute-cron
on:
  schedule:
    - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron API route
        run: |
          curl --request POST \
          --url 'https://poool.party/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'